# Generated by Django 2.2.7 on 2019-11-15 16:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Order received'), (1, 'Order will be processed'), (2, 'Order will be shipped'), (3, 'Order delivered'), (-1, 'Order canceled')])),
                ('created_at', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_api.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flavour', models.CharField(choices=[('margarita', 'Pizza Margarita'), ('marinara', 'Marinara Pizza'), ('salami', 'Salami Pizza')], max_length=150)),
                ('quantity', models.IntegerField(default=1)),
                ('size', models.IntegerField(choices=[(26, 'Small - 26cm'), (28, 'Medium - 28cm'), (30, 'Large - 30cm'), (32, 'Extra large - 32cm')])),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_api.Orders')),
            ],
        ),
    ]
