# Generated by Django 2.2.7 on 2019-11-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_api', '0002_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pizza_api.Orders'),
        ),
    ]
